# Small Data Extraction using Web Scraping

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from bs4 import BeautifulSoup

In [6]:
book_name=[]
product_price=[]
stock_availabilit=[]

In [7]:
for i in range(1,51):
    url="https://books.toscrape.com/catalogue/page-{i}.html".format(i=i)
    headers = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"
    }
    
    respond=requests.get(url,headers=headers).text
    soup=BeautifulSoup(respond,"html")

  
    for i in soup.find_all("li",class_="col-xs-6 col-sm-4 col-md-3 col-lg-3"):
            book_name.append(i.find("h3").text.strip())
            product_price.append(i.find("p",class_="price_color").text.strip())
            stock_availabilit.append(i.find("p",class_="instock availability").text.strip())
df=pd.DataFrame({"book_name":book_name,"product_price":product_price," stock_availabilit": stock_availabilit})
df["product_price(£)"]=df["product_price"].str.split("£").apply(lambda x:x[1])
df=df.drop(columns=["product_price"])
df

                            book_name  stock_availabilit product_price(£)
0                  A Light in the ...           In stock            51.77
1                  Tipping the Velvet           In stock            53.74
2                          Soumission           In stock            50.10
3                       Sharp Objects           In stock            47.82
4        Sapiens: A Brief History ...           In stock            54.23
..                                ...                ...              ...
995  Alice in Wonderland (Alice's ...           In stock            55.53
996    Ajin: Demi-Human, Volume 1 ...           In stock            57.06
997         A Spy's Devotion (The ...           In stock            16.97
998           1st to Die (Women's ...           In stock            53.98
999           1,000 Places to See ...           In stock            26.08

[1000 rows x 3 columns]

In [8]:
df.shape

(1000, 3)

In [28]:
df["book_name"].value_counts()
df["product_price(£)"]

0      51.77
1      53.74
2      50.10
3      47.82
4      54.23
       ...
995    55.53
996    57.06
997    16.97
998    53.98
999    26.08
Name: product_price(£), Length: 1000, dtype: object

In [29]:
df.describe()

                       book_name  stock_availabilit product_price(£)
count                       1000               1000             1000
unique                       992                  1              903
top     Harry Potter and the ...           In stock            44.18
freq                           6               1000                3